A little program that find out the words new to you from a text file.

HOWTO
=====

Find out the new words
----------------------

Put **pickupnewords.py** and **oldwords.dat** under same directory. Run::

  python pickupnewords.py /path/to/your/newords.txt

Remember the words you have known
---------------------------------

After

FILES
=====

*README.rst*
  This document itself.

*oldwords.dat*
  The basic words set the program has assumed that you have known.
  This file is generated by Python's pickle module.

  **needed by the program**

*oxford3000.txt*
  Original words fetching from the web, just text plain.

*pickupnewords.py*
  Main program
